---
title: "Developer onboarding - using renv"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Developer onboarding - using renv}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Overview

The `renv` package provides project-local R dependency management to your projects. It helps manage library paths (and other project-specific state) to help isolate your project’s R dependencies. The `renv` package helps you create **r**eproducible **env**ironments for your R projects. It will make your R packages more **isolated**, **portable** and **reproducible**.

## Actions performed only once in the repo

First someone initialized a new project-local environment with a private R library - which can be done via `renv::init()`.

This action will result in the creation of a lockfile - named `renv.lock` in the root directory. The lock file contains a ton of environment metadata, including the developers installed packages & versions, plus the repository source where those packages were installed from. It's important to note that this dev team will use a repo source that does not point at production CRAN, because we want a stable (aka unchanging) source for pkgs. As such, the `lockfile` should (and will) only be upgraded if there is a need for an important new feature that relies on the latest version of a new or existing pkg in the lock file.

Each developer working within the repo for the first time will need sync up with with the packages stored in the `renv.lock` file. The first time you do this, you'll need to run `renv::activate()` which will ask for you to confirm you decision. Note that these new pkg installations will only impact this R project, and not your R system library stored elsewhere.

## If new packages installations are needed

Work in the project as usual and as new dependencies are justified, save the current state of the project library with `renv::snapshot()`. This result will be saved into a lockfile - `renv.lock`. If you are just testing a new package out and want to revert back to the pkgs line up stored in the lock file, run `renv::restore()`. Similarly, anytime your fellow developer submits a PR requesting a change in the lock file, you'll need to run `renv::restore()` to sync up your development with the rest of the team.

If at any time your out of sync the `renv.lock` file, you can run `renv::status()` to see which packages are ahead or behind the lock file.


## How to ignore files & pkgs in the lock file

By default `renv` ignores all files stated in the `.gitignore` file. If you want to extend that further, you can use a `.renvignore` file - which is specified similar to the `.gitignore` file.

In addition, you can ignore package that `renv` thinks you need to add to the lock file using the following command:

`renv::settings$ignored.packages("<<package name>>")`


## Cache Location on different Operating Systems

* Linux	`~/.local/share/renv`
* macOS	`~/Library/Application Support/renv`
* Windows	`%LOCALAPPDATA%/renv`

## References
* [github.io/renv/](https://rstudio.github.io/renv/)
* [Introduction to renv](https://rstudio.github.io/renv/articles/renv.html)