---
title:    "R Package Risk Assessment"
subtitle: "Report for `r params$pkg[['name']]()`"
author:   "Author (Role): `r params$user_name` (`r params$user_role `)"
date:     "Report Date: `r format(Sys.time(), '%B %d, %Y')`"
always_allow_html: true
output:
  word_document:
    md_extensions: +raw_html-markdown_in_html_blocks
    pandoc_args: ['--lua-filter', 'read_html.lua']
params:
  pkg: NA
  riskmetric_version: NA
  user_name: NA
  user_role: NA
  overall_comments: NA
  mm_comments: NA
  cm_comments: NA
  maint_metrics: NA
  com_metrics: NA
  com_metrics_raw: NA
  downloads_plot_data: NA
---

```{r setup, include=FALSE}
library(knitr)
library(shiny)
library(ggplot2)
library(plotly)

knitr::opts_chunk$set(echo = F, fig.width = 5.5, fig.height = 3.4)
```


```{r functions, include=FALSE, message=FALSE, warning=FALSE}
outputComments <- function(pkg_name, comments){
  ifelse(
    length(comments$user_name) == 0, 
    "No comments",
    paste0(
      "<div class='well'>",
      icon("user-tie"), " ", "user: ", comments$user_name, ", ", 
      icon("user-shield"), " ", "role: ", comments$user_role, ", ",
      icon("calendar-alt"), " ", "date: ", comments$added_on, ': ',
      comments$comment,
      "</div>",
      collapse = ""
    )
  )
}
```

<br>

```{r general_pkg_info}
tagList(
  strong('Package:'),      br(), getElement(params$pkg, 'name')(),         br(), br(),
  strong('Version:'),      br(), getElement(params$pkg, 'version')(),      br(), br(),
  strong('Title:'),        br(), getElement(params$pkg, 'title')(),        br(), br(),
  strong('Description:'),  br(), getElement(params$pkg, 'description')(),  br(), br(),
  strong('Author:'),       br(), getElement(params$pkg, 'author')(),       br(), br(),
  strong('Maintainer:'),   br(), getElement(params$pkg, 'maintainer')(),   br(), br(),
  strong('License:'),      br(), getElement(params$pkg, 'license')(),      br(), br(),
  strong('Published:'),    br(), getElement(params$pkg, 'published')(),    br(), br(),
  strong('Overall Risk:'), br(), ifelse(params$pkg[['decision']]() == '', 'Pending', params$pkg[['decision']]())
)
```


```{r overall_comments}
tagList(
  h5('Overall Comments', style = "padding-bottom:10px;"),
  wellPanel(
    HTML(outputComments(
      pkg_name = params$pkg$name(),
      comments = params$overall_comments()))
  )
)
```


```{r maintenance_metrics}
tagList(br(), h5('Maintenance Metrics'), br())
```


```{r maintenance_metrics_table}
params$maint_metrics() %>%
  mutate(
    `Metric Name` = title,
    `Metric Description` = desc,
    `Metric Value` = value
  ) %>%
  select(`Metric Name`, `Metric Description`, `Metric Value`) %>%
  knitr::kable(format = 'pandoc')
```


```{r maintenance_metrics_comments}
tagList(
  br(),
  h5('Comments'),
  HTML(outputComments(
    pkg_name = params$pkg$name(),
    comments = params$mm_comments()))
)
```


```{r community_metrics, warning=FALSE, message=FALSE}
tagList(br(), h5("Community Usage Metrics"), br())
```


```{r community_metrics_table, warning=FALSE, message=FALSE, error=FALSE, results='HIDE', echo=FALSE}
params$com_metrics() %>%
  mutate(
    `Metric Name` = title,
    `Metric Description` = desc,
    `Metric Value` = value
  ) %>%
  select(`Metric Name`, `Metric Description`, `Metric Value`) %>%
  knitr::kable(format = 'pandoc')
```


```{r community_metrics_plot_title}
tagList(
  br(),
  h5('Number of Downloads by Month/Year')
)
```


```{r community_metrics_plot}
params$com_metrics_raw() %>%
  mutate(day_month_year = glue('1-{month}-{year}')) %>%
  mutate(day_month_year = as.Date(day_month_year, "%d-%m-%Y")) %>%
  mutate(month = month.name[month]) %>%
  arrange(day_month_year) %>%
  distinct(month, year, .keep_all = TRUE) %>%
  ggplot(aes(x = day_month_year, y = downloads)) +
  geom_point() +
  geom_line() +
  scale_x_date(date_breaks = "3 months", date_labels = "%m-%Y") +
  labs(
    x = 'Month/Year',
    y = 'Downloads'
  )
```


```{r community_metrics_comments}
tagList(
  br(),
  h5('Comments'),
  HTML(outputComments(
    pkg_name = params$pkg$name(),
    comments = params$cm_comments()))
)
```

