---
title:    "R Package Risk Assessment"
subtitle: "Report for `r params$pkg$name()`"
author:   "Author (Role): `r params$user_name` (`r params$user_role `)"
date:     "Report Date: `r format(Sys.time(), '%B %d, %Y')`"
always_allow_html: true
output: 
  html_document:
    theme:
      bootswatch: lux
runtime: shiny
params:
  pkg: NA
  riskmetric_version: NA
  user_name: NA
  user_role: NA
  overall_comments: NA
  mm_comments: NA
  cm_comments: NA
---

```{r setup, include=FALSE}
library(knitr)
library(shiny)
library(shinyjs)

knitr::opts_chunk$set(echo = F, fig.width = 5.5, fig.height = 3.4)
```


```{r gather_pkg, echo=FALSE, include=FALSE, message=FALSE, warning=FALSE}

```

<br>

```{r general_pkg_info}
h5('General Information')

tagList(
  h6('Package:'), params$pkg$name(),
  h6('Version:'), params$pkg$version(),
  h6('Title:'), params$pkg$title(),
  h6('Description:'), params$pkg$description(),
  h6('Author:'), params$pkg$author(),
  h6('Maintainer:'), params$pkg$maintainer(),
  h6('License:'), params$pkg$license(),
  h6('Published:'), params$pkg$published(),
  h6('Overall Risk:'), ifelse(params$pkg$decision() == '', 'Pending', params$pkg$decision())
)
```


```{r overall_comments}
tagList(
  h5('Overall Comments', style = "padding-bottom:10px;"),
  wellPanel(
    HTML(showComments(
      pkg_name = params$pkg$name(),
      comments = params$overall_comments()))
  )
)
```


```{r maintenance_metrics_comments}
tagList(
  h5('Comments', style = "padding-bottom:10px;"),
  wellPanel(
    HTML(showComments(
      pkg_name = params$pkg$name(),
      comments = params$mm_comments()))
  )
)
```


```{r community_metrics_comments}
tagList(
  h5('Comments', style = "padding-bottom:10px;"),
  wellPanel(
    HTML(showComments(
      pkg_name = params$pkg$name(),
      comments = params$cm_comments()))
  )
)
```

<style>
.title {
font-size: 1.5rem;
}

.subtitle, .author, .date {
font-size: 1.1rem;
}
</style>
