INSERT INTO metric (name, description, class, weight) values 
('has_vignettes', '', 'maintenance', 1),
('has_news', '', 'maintenance', 1),
('has_bug_reports_url', '', 'maintenance', 1),
('has_website', '', 'maintenance', 1),
('news_current', '', 'maintenance', 1),
('has_maintainer', '', 'maintenance', 1),
('has_source_control', '', 'maintenance', 1),
('export_help', '', 'maintenance', 1),
('bugs_status', '', 'maintenance', 1),
('license', '', 'maintenance', 1),
('covr_coverage', '', 'test', 0),
('r_cmd_check', '', 'test', 0),
('remote_checks', '', 'test', 0),
('downloads_1yr', '', 'community', 1);